// Copyright (C) 2021  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 842 10/21/2021)
// Created on Wed Apr 17 04:39:01 2024

uart_transmitter_top uart_transmitter_top_inst
(
	.clk_50M(clk_50M_sig) ,	// input  clk_50M_sig
	.switch_0(switch_0_sig) ,	// input  switch_0_sig
	.serial_out(serial_out_sig) ,	// output  serial_out_sig
	.busy(busy_sig) ,	// output  busy_sig
	.busy_LED(busy_LED_sig) ,	// output  busy_LED_sig
	.serial_out_LED(serial_out_LED_sig) 	// output  serial_out_LED_sig
);

